name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Make build directory
        run: mkdir -p build

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build binary
        run: |
          # Generate spec file if it doesn't exist
          if [ ! -f "hosts_updater.spec" ]; then
            pyinstaller --onefile hosts_updater.py --specpath .
          fi
          ./build.sh
          mkdir -p build
          rm -rf build/hosts_updater  # Remove if exists as directory
          cp -f dist/hosts_updater build/  # Force copy

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
